import streamlit as st
import requests

# ---------------- CONFIGURATION ----------------
BACKEND_URL = "http://localhost:8000/chat"

st.set_page_config(
    page_title="Hybrid AI Chat", 
    page_icon="🤖",
    layout="wide"  # 'wide' layout looks more like a real app
)

# ---------------- SIDEBAR (The "Gemini/ChatGPT" Style) ----------------
with st.sidebar:
    st.title("🤖 Hybrid AI")
    
    # 1. Action Buttons
    if st.button("➕ New Chat", use_container_width=True):
        st.session_state.messages = []
        st.rerun()

    st.markdown("---")
    
    # 2. Settings / Info
    st.subheader("⚙️ System Architecture")
    st.markdown("""
    - **🧠 Router:** Fast API (Auto-detect)
    - **⚡ Text:** Groq (Llama 3)
    - **🎨 Image:** Google Gemini (Imagen)
    - **🛡️ Backup:** Pollinations.ai
    """)
    
    st.markdown("---")
    
    # 3. Status Indicator (Optional Visual)
    st.success("🟢 System Online")

# ---------------- MAIN CHAT INTERFACE ----------------

# Custom CSS to make it look cleaner (optional)
st.markdown("""
    <style>
    .stChatMessage {background-color: transparent;} 
    /* Hide the default Streamlit top menu for a cleaner look */
    #MainMenu {visibility: hidden;}
    footer {visibility: hidden;}
    </style>
    """, unsafe_allow_html=True)

st.title("💬 Multi Model ChatBot")
st.caption("🚀 Powered by Groq & Gemini")

# ---------------- SESSION STATE ----------------
if "messages" not in st.session_state:
    st.session_state.messages = []

# ---------------- RENDER HISTORY ----------------
for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        if message["type"] == "text":
            st.markdown(message["content"])
        elif message["type"] == "image":
            st.image(message["content"], caption="Generated Image", use_column_width=True)
            if "meta" in message:
                with st.expander("🔍 See Model Details"):
                    st.json(message["meta"])

# ---------------- INPUT HANDLER ----------------
if prompt := st.chat_input("Type a message..."):
    
    # 1. Display User Message
    with st.chat_message("user"):
        st.markdown(prompt)
    st.session_state.messages.append({"role": "user", "type": "text", "content": prompt})

    # 2. Call Backend
    with st.chat_message("assistant"):
        with st.spinner("Thinking..."):
            try:
                response = requests.post(
                    BACKEND_URL, 
                    json={"prompt": prompt, "mode": "auto"},
                    timeout=60
                )
                
                if response.status_code == 200:
                    data = response.json()
                    output = data["output"]
                    result = output["result"]
                    
                    # Check content type
                    content_type = result.get("type", "text")
                    
                    if content_type == "image":
                        image_url = result.get("image_url")
                        st.image(image_url, caption=f"Generated by {data['provider']}", use_column_width=True)
                        st.session_state.messages.append({
                            "role": "assistant", 
                            "type": "image", 
                            "content": image_url,
                            "meta": data
                        })
                    else:
                        text_content = result.get("text", "No response text")
                        st.markdown(text_content)
                        st.session_state.messages.append({
                            "role": "assistant", 
                            "type": "text", 
                            "content": text_content
                        })
                else:
                    st.error(f"Error {response.status_code}: {response.text}")

            except requests.exceptions.ConnectionError:
                st.error("❌ Could not connect to backend. Is 'app.py' running?")
            except Exception as e:
                st.error(f"An error occurred: {e}")